# Generated by Django 2.2.2 on 2019-06-26 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
